# GitHub Container Registryへ、イメージをビルドしてpushします。
name: イメージ作成とpush
on:
  push:
    branches:
      - main
  workflow_dispatch:


# GHCRへプッシュできるよう権限を設定
permissions:
  contents: read
  packages: write
  id-token: write

env:
    ACT: false

jobs:
    make_serial:
        runs-on: ubuntu-latest
        outputs:
          serial: ${{ steps.serial.outputs.serial }}
        steps:
        - name: 日時のシリアル番号を作成(後でタグとして使います)
          id: serial
          run: |
            echo "serial=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
    build:
        strategy:
          fail-fast: true
          matrix:
            # linux/amd64ならubuntu-24.04で、
            # linux/arm64ならubuntu-24.04-arm64でビルドを行う
            platform: [linux/amd64, linux/arm64]
            runner: [ubuntu-24.04, ubuntu-24.04-arm64]
            ignore:
              - platform: linux/arm64
                runner: ubuntu-24.04
              - platform: linux/amd64
                runner: ubuntu-24.04-arm64
        runs-on: ${{ matrix.runner }}
        name: イメージビルド(${{ matrix.platform }})
        needs: make_serial
        # amd64とarm64のビルドのため、ストラテジーを設定
        # それぞれ使用するランナーはubuntu-24.04およびubuntu-24.04-arm64とする
        steps:
        - name: ソースの取得
          uses: actions/checkout@v4
        - name: Dockerの準備
          uses: docker/setup-buildx-action@v2
        - name: Dockerのストレージの準備(qemu)
          uses: docker/setup-qemu-action@v2
        - name: Dockerのログイン
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            # GitHubのトークンを使用して、GHCRへログインします。
            # これにより、イメージをpushすることができるようになります。
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: イメージビルドと送信
          uses: docker/build-push-action@v3
          with:
            context: .
            push: ${{ env.ACT != 'false' }}
            load: ${{ env.ACT == 'false' }}
            tags: |
                ghcr.io/${{ github.repository }}:${{ needs.make_serial.outputs.serial }}
                ghcr.io/${{ github.repository }}:latest
            platforms: ${{ matrix.platform }}
            build-args: |
                # ビルド時に必要な引数を指定します。
                # ここでは、シリアル番号をARGとして渡しています。
                SERIAL=${{ needs.make_serial.outputs.serial }}

                
            